# -*- coding: utf-8 -*-
"""python programming02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWp9NhCCkNg5o0unroJx05E_B9_asdBG
"""

a =[]
while(1):
  a.append('1')



"""Tuple usage"""

coordinates =(1,2)

coordinates[0]

coordinates [0] = 10



"""functions and return statements"""

def sum1(a,b):
  return (int(a)+int(b))
print("this lets you add two number")
a = input("enter the first number")
b = input("enter the second number")
print("the number is"+ str(sum1(a,b)))

num1 = True
if not(num1):
  print("hello")
elif not(not(num1)):
  print("hi")

"""If statements in the comaprisson"""

def find(num1,num2,num3):
  if(int(num1)>int(num2))and (int(num1)>int(num3)):
      return num1
  elif  (int(num2)>int(num1))and (int(num2)>int(num3)):
      return num2
  else:
      return num3    
    

num1 = input("enter the num1:")
num2 = input("enter the num2:")
num3 = input("enter the num3:")
find(num1,num2,num3)

num1 = float(input("enter the first number"))
num2 = float(input("enter the second number number"))
op = input("Sum , mult , div , minus")

if op =="Sum":
  print(num1+num2)
elif op == "mult":
  print(num1*num2)  
elif op == "div":
  print(num1/num2) 

elif op =="minus":
  print(num1-num2) 
else:
  print("invalid operator")

ab = {a : 'chetan', b :'deepak'}

print(ab.get('c','invalid key'))





"""while loop"""

i =10
print(i)
while(i<100):
  print(i+10)
  i=i+10

do

i=1
do
print(i)
i=i+1
while(i<5):



"""game"""

secret = "hello"
yourword=""
count =3
while yourword!=secret:
   if (count ==0):
     print("you have no guesses left")
     xy ="loose"
     break
   else: 
     yourword = input("guees the word ")
     count = count -1
     xy = "win"
  

print("you " +xy+ ".")

x=['one','two','three']
y=[]
for i in x:
   y = x.copy()

z = y.copy()
print(y)
print(z)
if(z == x):
  print("palendrome")

pow(2,3)

help pow

pow help

number_grid = [
        [1,2,3],
        [4,5,6],
        [7,8,9] ,
        [0]      

]

number_grid[1]



number_grid[1][1]

